name: A workflow for go test
on: [push,pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
          id: go
      - name: Code
        uses: actions/checkout@v1
      - name: Lint
        uses: sjkaliski/go-github-actions/fmt@v1.0.0
        run: |
          
          cd ./k8s-deploy/pkg/
          go fmt -l .
          # go mod vendor
          # # modules-download-mode: vendor
          # curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b . latest
          # # curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
          # ./golangci-lint run ./... --timeout
  test:
    # needs: Lint
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v1
        with:
            go-version: 1.14
      - name: Code
        uses: actions/checkout@v1
      - name: Test
        run: |
          cd ./k8s-deploy/pkg/api
          go test
          # go test router.go router_test.go 
          # go test job.go job_test.go
        