name: A workflow for docker deploy ci
on: push
jobs:
  build:
    name: Docker deploy action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: generate config
      if: success()
      run: |
        cd ./docker-deploy
        bash generate_config.sh
        echo "check output:"
        ls ./outputs
        cd ../
#      - uses: ./action-dockerdeploy
#        with:
#          MY_NAME: "Mona"

    - name: docker deploy
      if: success()
      run: |
        # test ipconfig
        ifconfig
        # sudo mkdir -p /data/projects/fate
        # echo "docker-compose begin:"
        # cd ./docker-deploy
        # bash docker_deploy.sh all
        # echo "check containers"
        # docker ps
        # echo "run_toy_example:"
        # docker exec -it confs-10000_python_1 bash
        # cd /data/projects/fate/python/examples/toy_example/
        # python run_toy_example.py 10000 1000 1